import type { Component } from 'vue'
import {
  Square,
  SquareDashed,
  Container,
  LayoutGrid,
  PanelTop,
  PanelBottom,
  Navigation,
  Type,
  Heading,
  Pilcrow,
  Baseline,
  Tag,
  Image,
  Video,
  RectangleHorizontal,
  FormInput,
  TextCursorInput,
  SquareCheck,
  CircleDot,
  SquareChevronDown,
  MousePointerClick,
  List,
  Link,
  Component as ComponentIcon,
  Layers,
  FileText,
  GalleryHorizontalEnd,
  Table,
  Rows3,
  Columns3,
  TableProperties,
  Smile,
  CircleCheck,
  CircleAlert,
} from 'lucide-vue-next'
import { isComponentType } from './components'

const ICONS: Record<string, Component> = {
  body: Square,
  section: Square,
  div: SquareDashed,
  container: Container,
  grid: LayoutGrid,
  header: PanelTop,
  footer: PanelBottom,
  nav: Navigation,
  main: Square,
  article: FileText,
  aside: RectangleHorizontal,
  text: Type,
  heading: Heading,
  h1: Heading,
  h2: Heading,
  h3: Heading,
  h4: Heading,
  h5: Heading,
  h6: Heading,
  paragraph: Pilcrow,
  span: Baseline,
  label: Tag,
  image: Image,
  video: Video,
  icon: Smile,
  form: RectangleHorizontal,
  'form-success': CircleCheck,
  'form-error': CircleAlert,
  input: FormInput,
  textarea: TextCursorInput,
  checkbox: SquareCheck,
  radio: CircleDot,
  fieldset: SquareDashed,
  legend: Tag,
  dropdown: SquareChevronDown,
  select: SquareChevronDown,
  button: MousePointerClick,
  list: List,
  'list-item': List,
  link: Link,
  'collection-list': Layers,
  'collection-item': FileText,
  slider: GalleryHorizontalEnd,
  table: Table,
  thead: TableProperties,
  tbody: Rows3,
  tr: Rows3,
  th: Columns3,
  td: Columns3,
}

/** the palette/header icon for an element type (components → the component glyph) */
export function elementIcon(type: string | undefined): Component {
  if (!type) return Square
  if (isComponentType(type)) return ComponentIcon
  return ICONS[type] ?? Square
}
