export const ELEMENTS_DATA = {
  body: { tag: 'div', suggest: 'section' },
  section: { tag: 'section', suggest: 'div' },
  div: { tag: 'div', suggest: 'h2' },
  container: { tag: 'div', suggest: 'div' },
  grid: { tag: 'div', suggest: 'div' },
  header: { tag: 'header', suggest: 'nav' },
  footer: { tag: 'footer', suggest: 'text' },
  article: { tag: 'article', suggest: 'h2' },
  nav: { tag: 'nav', suggest: 'link' },
  main: { tag: 'main', suggest: 'section' },
  aside: { tag: 'aside', suggest: 'h3' },
  text: { tag: 'div', defaultContent: 'Lorem ipsum' },
  h1: { tag: 'h1', defaultContent: 'Lorem ipsum' },
  h2: { tag: 'h2', defaultContent: 'Lorem ipsum' },
  h3: { tag: 'h3', defaultContent: 'Lorem ipsum' },
  h4: { tag: 'h4', defaultContent: 'Lorem ipsum' },
  h5: { tag: 'h5', defaultContent: 'Lorem ipsum' },
  h6: { tag: 'h6', defaultContent: 'Lorem ipsum' },
  heading: { tag: 'h2', defaultContent: 'Lorem ipsum' },
  label: { tag: 'label', suggest: 'span', seed: { type: 'span', content: 'Label' } },
  paragraph: { tag: 'p', defaultContent: 'Dolor sit amet' },
  span: { tag: 'span', defaultContent: 'Dolor sit amet' },
  blockquote: { tag: 'blockquote', suggest: 'paragraph' },
  figure: { tag: 'figure', suggest: 'image' },
  figcaption: { tag: 'figcaption', defaultContent: 'Caption' },
  list: { tag: 'ul', suggest: 'list-item' },
  'list-item': { tag: 'li', suggest: 'text' },
  image: { tag: 'img', void: true },
  icon: { tag: 'svg', void: true },
  video: { tag: 'video' },
  form: { tag: 'form', suggest: 'input' },

  'form-success': { tag: 'div', suggest: 'text' },
  'form-error': { tag: 'div', suggest: 'text' },
  input: { tag: 'input', void: true },
  textarea: { tag: 'textarea' },
  checkbox: { tag: 'input', void: true, attrs: { type: 'checkbox' } },
  radio: { tag: 'input', void: true, attrs: { type: 'radio' } },
  fieldset: { tag: 'fieldset', suggest: 'legend' },
  legend: { tag: 'legend', defaultContent: 'Legend' },
  dropdown: { tag: 'select', suggest: 'option' },
  select: { tag: 'select', suggest: 'option' },
  option: { tag: 'option', defaultContent: 'Option' },
  button: { tag: 'button', suggest: 'span', seed: { type: 'span', content: 'Button' } },
  link: { tag: 'a', suggest: 'span', seed: { type: 'span', content: 'Link' } },
  table: { tag: 'table', suggest: 'thead' },
  thead: { tag: 'thead', suggest: 'tr' },
  tbody: { tag: 'tbody', suggest: 'tr' },
  tr: { tag: 'tr', suggest: 'td' },
  th: { tag: 'th', suggest: 'text' },
  td: { tag: 'td', suggest: 'text' },
  'collection-list': { tag: 'div', suggest: 'div' },

  'list-empty': { tag: 'div', suggest: 'text' },
  'collection-item': { tag: 'div', defaultContent: '' },

  'custom-code': { tag: 'div', defaultContent: '' },

  slider: { tag: 'div', suggest: 'div' },
}
