// Builds src/lib/shared/lucideIcons.js — the bundled icon table the `:icon:`
// element picks from: icon name → the inner markup of its <svg>.
//
// Read from the lucide-vue-next package the editor's own chrome already uses,
// so the icons a user can pick are exactly the set (and the version) the app
// ships. That package only exports Vue components — the path data is closed
// over — so this reads each icon module's node list as text. Nothing is
// evaluated, and every icon is run through the inline-SVG sanitizer: one that
// does not survive it whole fails the build rather than shipping half-drawn.
//
// The table is COMMITTED (like the runtime bundles), so a fresh clone needs no
// build step. Re-run after bumping lucide-vue-next:
//
//   npm run build:icons

import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { lucideSvg } from '../src/lib/shared/svg.js'

const SOURCE = 'node_modules/lucide-vue-next/dist/esm/icons'
const TARGET = 'src/lib/shared/lucideIcons.js'

const ICON_RE = /createLucideIcon\("([a-z0-9-]+)",\s*\[([\s\S]*)\]\s*\);/
const NODE_RE = /\[\s*"([a-zA-Z]+)",\s*\{([^}]*)\}\s*\]/g
const ATTR_RE = /(?:"([^"]+)"|([A-Za-z][A-Za-z0-9]*))\s*:\s*"([^"]*)"/g

const version = JSON.parse(readFileSync('node_modules/lucide-vue-next/package.json', 'utf8'))
  .version as string

const icons: [string, string][] = []
for (const file of readdirSync(SOURCE).sort()) {
  if (!file.endsWith('.js') || file === 'index.js') continue
  const source = readFileSync(join(SOURCE, file), 'utf8')
  const icon = source.match(ICON_RE)
  if (!icon) throw new Error(`${file}: no icon definition found`)
  const name = icon[1]!

  let inner = ''
  let nodes = 0
  for (const node of icon[2]!.matchAll(NODE_RE)) {
    const attrs = [...node[2]!.matchAll(ATTR_RE)]
      .map((a) => [a[1] ?? a[2]!, a[3]!] as const)
      .filter(([key]) => key !== 'key')
      .map(([key, value]) => ` ${key}="${value}"`)
      .join('')
    inner += `<${node[1]}${attrs}/>`
    nodes++
  }
  if (!nodes) throw new Error(`${name}: no shapes found`)

  // the sanitizer is what every renderer trusts — an icon it would alter is
  // an icon that would not render as drawn
  const safe = lucideSvg(name, inner)
  const kept = safe.slice(safe.indexOf('>') + 1, safe.lastIndexOf('</svg>'))
  if (kept !== inner) throw new Error(`${name}: the sanitizer changed this icon\n  ${inner}\n  ${kept}`)
  icons.push([name, inner])
}

const body = icons.map(([name, inner]) => `  ${JSON.stringify(name)}: ${JSON.stringify(inner)},`).join('\n')
writeFileSync(
  TARGET,
  `// GENERATED by scripts/build-icons.ts from lucide-vue-next ${version} — do not edit.
// Re-run \`npm run build:icons\` after bumping the package.
//
// Icon name → the inner markup of its <svg>; wrap one with \`lucideSvg\`
// (./svg.js). Never import this statically from editor code: it is the whole
// icon set, and the picker loads it on demand.
//
// Lucide is ISC licensed — Copyright (c) for portions of Lucide are held by
// Cole Bemis 2013-2022 as part of Feather (MIT). All other copyright (c) for
// Lucide are held by Lucide Contributors 2022.
export const LUCIDE_VERSION = ${JSON.stringify(version)}
export const LUCIDE_ICONS = {
${body}
}
`,
)
console.log(`${icons.length} icons written to ${TARGET}`)
